[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
strip = { path = "/usr/bin/arm-linux-gnueabihf-strip" }
objcopy = { path = "/usr/bin/arm-linux-gnueabihf-objcopy" }

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
strip = { path = "/usr/bin/aarch64-linux-gnu-strip" }
objcopy = { path = "/usr/bin/aarch64-linux-gnu-objcopy" }

[dependencies]
opencascade = "0.1"
image = "0.24"
